### ISSUE TITLE
Wrong «copy buttons» in upload-pictures window

### ISSUE THREAD

**Issue by vkapas** [itmages/itmages-libitmages#4]
I found what some «copy buttons» (e.g. «BB big picture») in upload-pictures window is wrong.
1. If I select «HTML **preview** for forum» and click to chain icon, upload-pictures copy «HTML **full size image**».
2. For «BB **preview** for forum» upload-pictures copy «BB **full size image**».
3. For «BB **full size image**» upload-pictures copy «BB **preview** for forum».

<a target='_blank' href='http://itmages.ru/image/view/2583702/01548f08'><img src='http://storage3.static.itmages.ru/i/15/0526/h_1432649692_9079415_01548f08d8.png' ></a>

**Comment by korotovsky** [comment]
Fixed in https://github.com/itmages/itmages-libitmages/commit/87fdf97db8416b50c6d03a835d561697eb503d5a

**Comment by korotovsky** [comment]
Updates have been published to our PPA.
